### ISSUE TITLE
Meeting 10/21/19: TDSD Application Check-In

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-knack-development-review#23]
### Objective 
Project team debrief on the implementation of the TDSD application that went live on 10/1. Identify any blockers to or resources needed for full user adoption. 

### Participants
Sangeeta Jain, Nathan Aubert, Joe Calabrese, Amber Mitchell, Diana Martin, Tracy Linder, Surbhi Bakshi

### Date/Time/Location
Oct 21, 2019 / 1:30-2:30pm / ATD Barton Oaks Rio Grande

### Agenda
* Is the application meeting the business needs? Why or why not?
* User Adoption:
    * How do you feel the users are doing in utilizing this tool to meet business needs? (Project Managers, Vision Team Reviewers)
    * Identify any blockers to user adoption and brainstorm solutions
* Training Needs:
    * If not already identified, discuss any training needs. How will these needs be met?
* Test Data: 
    * Has any test data been entered that needs to be deleted? 

### Tasks Identified During Meeting:
- [x] (Diana) On the 'My Reviews' page, add text under the 'Previously Reviewed' section to explain that the items there cannot be edited…. Read only. 
- [x] (Diana) The review due dates still may not be calculating based on the correct information
- [x] (Diana) Make the "area" field mandatory
- [x] (Diana) Finalize the user guide & send it out
    * Joe wants to see it too. 
- [x] (Diana) Add a link to the user guide in the app, wherever it makes the most sense
- [x] (Diana) On the Development Review Details page, rename the button +Add Review Comment to  +Add Reviewer 
    * Move the button to above the Reviewer Comments table
    * Update the user guide
- [x] (Diana) On Development Reviews page, update the sorting order of the open cases. The logic is in Diana's head. 
    - [x] Also add 'Count of Cycles'    
- [x] (Tracy) Add an issue for TDSD Phase 2, and add an item for Development Assessment needs
- [ ] (Sangeeta) Schedule training  

------
- [x] Schedule meeting
- [x] Meet
- [x] Attach meeting notes to this issue
- [x] Create resulting issues
